# Add in /homeassistant/configuration.yaml
# input_boolean:
#   cycle_active:
#     name: Cycle Active
#     initial: off
#     icon: mdi:repeat

blueprint:
  name: Device On/Off Cycle with Timer
  description: Automation that turns a device on for a set number of minutes at regular intervals within a defined time window.
  domain: automation
  input:
    device_entity:
      name: Device or Entity
      description: The device or entity to turn on/off.
      selector:
        entity:
          domain: switch

    interval_minutes:
      name: Interval (minutes)
      description: Number of minutes between each device activation.
      default: 30
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes

    on_duration:
      name: On duration (minutes)
      description: How long the device stays on.
      default: 30
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes

    start_time:
      name: Start time
      description: Start time of the on/off cycle.
      default: "08:00:00"
      selector:
        time:

    end_time:
      name: End time
      description: End time of the on/off cycle.
      default: "20:00:00"
      selector:
        time:

mode: restart

trigger:
  - platform: time_pattern
    minutes: "/1"   # Fires every minute

condition:
  - condition: template
    value_template: >
      {{ states('sensor.time') >= (states('input_datetime.start_time') | default('08:00:00')) 
         and states('sensor.time') <= (states('input_datetime.end_time') | default('20:00:00')) }}
  - condition: state
    entity_id: input_boolean.cycle_active
    state: "off"     # Ensures the loop is not already running

action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.cycle_active   # Marks the cycle as active
  - service: switch.turn_on
    target:
      entity_id: !input device_entity

  - delay:
      minutes: !input on_duration

  - service: switch.turn_off
    target:
      entity_id: !input device_entity

  - delay:
      minutes: !input interval_minutes

  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.cycle_active   # Marks the cycle as finished
